* 01. Setup NixOS to use Nvidia drivers with CUDA support

As NixOS already has good support for using Nvidia drivers, this is going to be one of the easiest steps. Make a note of the CUDA version installed, as it'll be important for the steps later.

** Start using Nvidia drivers

As  mentioned in the official NixOS wiki, installation of the driver is a simple switch of configuration. https://nixos.wiki/wiki/Nvidia

This setup is used for a RTX 30 series card, and using the stable driver on 21.05 channel. (Driver version 460.73.01 on 7th August 2021). Please check the wiki link above to see if you're using a relatively old card and might need legacy drivers.

Having the GPU configuration in a separate file makes it easy to include in the main configuration.

*** nvidia_gpu.nix

#+begin_src nix :tangle ./01-files/nvidia_gpu.nix
  { config, lib, pkgs, ... }:


  {
    services.xserver.videoDrivers = [ "nvidia" ];
  }
#+end_src

Include the gpu config in the main configuration

*** configuration.nix

#+begin_src nix :tangle ./01-files/configuration.nix
  { config, lib, pkgs, ... }:

  {
    imports = [
      ./hardware-configuration.nix

      .
      .

      # gpu
      ./nvidia_gpu.nix

      .
      .

    ];

  .
  .
  .
#+end_src

Rebuild nixos and wait for the driver to be successfully installed. Reboot and continue.

** Pay attention to the driver version and CUDA version

At this point, you should have a functioning Nvidia GPU on your NixOS host. Check the wiki and forums again for any issues.

Check the general information about your GPU. Make a note of the CUDA driver version.

#+begin_src shell
  > nvidia-smi
  Sat Aug  7 14:50:47 2021
  +-----------------------------------------------------------------------------+
  | NVIDIA-SMI 460.73.01    Driver Version: 460.73.01    CUDA Version: 11.2     |
  |-------------------------------+----------------------+----------------------+
  | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
  | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
  |                               |                      |               MIG M. |
  |===============================+======================+======================|
  |   0  GeForce RTX 3090    Off  | 00000000:01:00.0  On |                  N/A |
  |  0%   47C    P5    48W / 370W |    508MiB / 24265MiB |      1%      Default |
  |                               |                      |                  N/A |
  +-------------------------------+----------------------+----------------------+

  +-----------------------------------------------------------------------------+
  | Processes:                                                                  |
  |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
  |        ID   ID                                                   Usage      |
  |=============================================================================|
  |    0   N/A  N/A      1261      G   ...xorg-server-1.20.11/bin/X      423MiB |
  |    0   N/A  N/A      1754      G   ...cr2sz-picom-8.2/bin/picom       20MiB |
  |    0   N/A  N/A      4401      G   ...sh/.nix-profile/bin/kitty       22MiB |
  +-----------------------------------------------------------------------------+
#+end_src

** Install some useful tools (and benchmarks) on the NixOS host

The instruction below are for running them without permanent installation. Install them as needed.

#+begin_src shell
  nix-shell -p nvtop --run nvtop
  nix-shell -p glxinfo --run glxgears
  nix-shell -p unigine-valley --run valley
#+end_src

** Optionally, for i3 window manager, i3status-rust supports Nvidia GPU blocks

Check the instructions on i3status-rust wiki. https://github.com/greshake/i3status-rust/blob/master/doc/blocks.md#nvidia-gpu
