* 01. Setup NixOS to use Nvidia drivers with CUDA support

As NixOS already has good support for using Nvidia drivers, this is going to be one of the easiest steps. Make a note of the CUDA version installed, as it'll be important for the steps later.

** Start using Nvidia drivers

As  mentioned in the official NixOS wiki, installation of the driver is a simple switch of configuration. https://nixos.wiki/wiki/Nvidia

This setup is used for a RTX 30 series card, and using the stable driver on 24.11 channel. (Driver Version: 565.77 on Mar 12th 2025). Please check the wiki link above to see if you're using a relatively old card and might need legacy drivers.

Having the GPU configuration in a separate file makes it easy to include in the main configuration.

*** nvidia_gpu.nix

#+begin_src nix :tangle ./01-files/nvidia_gpu.nix
  { config, lib, pkgs, ... }:

  {

    services.xserver.videoDrivers = [ "nvidia" ];

    hardware.nvidia = {
      open = false;
      nvidiaSettings = true;
      modesetting.enable = true;

      package = config.boot.kernelPackages.nvidiaPackages.stable;
    };

  }
#+end_src

Include the gpu config in the main configuration

*** configuration.nix

#+begin_src nix :tangle ./01-files/configuration.nix
  { config, lib, pkgs, ... }:

  {
    imports = [
      ./hardware-configuration.nix

      .
      .

      # gpu
      ./nvidia_gpu.nix

      .
      .

    ];

  .
  .
  .
#+end_src

Rebuild nixos and wait for the driver to be successfully installed. Reboot and continue.

** Pay attention to the driver version and CUDA version

At this point, you should have a functioning Nvidia GPU on your NixOS host. Check the wiki and forums again for any issues.

Check the general information about your GPU. Make a note of the CUDA driver version.

#+begin_src shell
  > nvidia-smi
  Wed Mar 12 14:28:41 2025
  +-----------------------------------------------------------------------------------------+
  | NVIDIA-SMI 565.77                 Driver Version: 565.77         CUDA Version: 12.7     |
  |-----------------------------------------+------------------------+----------------------+
  | GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
  | Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
  |                                         |                        |               MIG M. |
  |=========================================+========================+======================|
  |   0  NVIDIA GeForce RTX 3090        Off |   00000000:01:00.0 Off |                  N/A |
  |  0%   44C    P8             20W /  370W |      15MiB /  24576MiB |      0%      Default |
  |                                         |                        |                  N/A |
  +-----------------------------------------+------------------------+----------------------+
  |   1  NVIDIA GeForce RTX 3090        Off |   00000000:02:00.0  On |                  N/A |
  |  0%   49C    P8             38W /  370W |    1782MiB /  24576MiB |     25%      Default |
  |                                         |                        |                  N/A |
  +-----------------------------------------+------------------------+----------------------+

  +-----------------------------------------------------------------------------------------+
  | Processes:                                                                              |
  |  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
  |        ID   ID                                                               Usage      |
  |=========================================================================================|
  |    0   N/A  N/A      1423      G   ...iz4y6d9ay-xorg-server-21.1.16/bin/X          4MiB |
  |    1   N/A  N/A      1423      G   ...iz4y6d9ay-xorg-server-21.1.16/bin/X        963MiB |
  +-----------------------------------------------------------------------------------------+
#+end_src

** Install some useful tools (and benchmarks) on the NixOS host

The instruction below are for running them without permanent installation. Install them as needed.

#+begin_src shell
  nix-shell -p nvtopPackages.full --run nvtop
#+end_src

** Optionally, for i3 window manager, i3status-rust supports Nvidia GPU blocks

https://greshake.github.io/i3status-rust/i3status_rs/blocks/nvidia_gpu/index.html
