services:

  lab:
    build:
      context: .
    command: /opt/bin/run.sh lab
    shm_size: '4gb'
    volumes:
      - ./app:/app
      - ~/.cache/huggingface:/cache/huggingface
    ports:
      - "8989:8989"
    environment:
      - HOST_USER_ID
      - HOST_GROUP_ID
      - XDG_CACHE_HOME=/cache
    deploy:
      resources:
        reservations:
          devices:
          - driver: cdi
            capabilities:
              - gpu
            device_ids:
              - nvidia.com/gpu=all
